name:        polonium
grade:       stable
version:     v1.2.0
summary:     Polonium is a stateless password manager based on PBKDF2.
description: Polonium is a stateless password manager based on PBKDF2

confinement: strict

base: core18

apps:
  polonium:
    command: bin/polo
    plugs: ['network']

parts:
  polonium:
    source: .
    plugin: nodejs
    nodejs-package-manager: npm
    build-packages: ['libcurl4-openssl-dev', 'git']