name:        polonium
grade:       stable
version:     v1.0.0
summary:     Polonium is a stateless password manager based on PBKDF2.
description: Polonium is a stateless password manager based on PBKDF2

confinement: "strict"

base: core18

apps:
  polonium:
    command: bin/polo

parts:
  polonium:
    source: ".."
    plugin: nodejs
