name:        polonium
grade:       stable
version:     v0.5.1
summary:     Polonium is a stateless password manager based on PBKDF2.
description: Polonium is a stateless password manager based on PBKDF2

confinement: "strict"

apps:
  polonium:
    command: bin/polo

parts:
  polonium:
    plugin: nodejs
    node-packages:
      - rgrannell1/polonium
